Bug fixes, add auto-update function, improve script speed, fix docs
Minor bug fixes:
- Installing on Windows/Linux requires sudo to install wrapper script. Updated docs to reflect this
- Script incorrectly identified Linux systems. Fixed OS checking
- Fixed minor formatting/style issues with error messages and output
- Increased time allotted to Docker Engine startup

New features:
- Script automatically checks GitHub for the latest version tag and checks whether an update is necessary
- ```caen version``` option added, which returns version of script and container
- ```caen update``` option added, which updates the container and script

See also #17, #18

diff --git a/caen b/caen
--- a/caen
+++ b/caen
@@ -1,16 +1,21 @@
 #!/bin/bash
+CAEN_SCRIPT_VER=v0.5
 
 # Shell settings to improve safety
-set -f -o pipefail
+set -fu -o pipefail
+CAEN_ARGS=${CAEN_ARGS:=" "}
 
 # Define our help message, docker flags, and env vars
+CAEN_REPO_NAME=${CAEN_REPO_NAME:=ghcr.io/derickson2402/dockerized-caen}
+CAEN_URL='https://github.com/derickson2402/Dockerized-CAEN'
+CAEN_VERSION=${CAEN_VERSION:=latest}
 CAEN_DEFAULT_ARGS="--rm -i --name caen-tainer -e TERM=${TERM:=linux}"
 CAEN_WORKING_DIR="-v '$(pwd):/code'"
 # NOTE: there is a space at the end to force newline printing
-HELP_MESSAGE=$(cat << EOF
+MESSAGE_HELP=$(cat << EOF
 Helper script for Dockerized-CAEN. To use, run the following:
 
-   $0 <program> [args]
+   $0 [program] [args]
 
 For example, running the following would run Valgrind on an
 executable called 'program.exe' with a '--flag' and input from a file:
@@ -24,14 +29,23 @@ You can specify a specific version of the container to run with the
 
 For more help, check me out on GitHub:
 
-     https://github.com/derickson2402/Dockerized-CAEN
+    ${CAEN_URL}
+ 
+EOF
+)
+MESSAGE_OS_ERROR=$(cat << EOF
+Hold up! We couldn't figure out what computer you're running! You
+can probably still run the container manually though, check me out
+on GitHub for help:
+
+    ${CAEN_URL}
  
 EOF
 )
 
 # Get OS information
 if [[ "$OSTYPE" == "linux-gnu"* ]]; then
-    if [[ -z "WSL_DISTRO_NAME" ]]; then
+    if [[ "${WSL_DISTRO_NAME:=unknown}" == "unknown" ]]; then
         HOST_OS=linux
     else
         HOST_OS=windows
@@ -39,44 +53,34 @@ if [[ "$OSTYPE" == "linux-gnu"* ]]; then
 elif [[ "$OSTYPE" == "darwin"* ]]; then
     HOST_OS=mac
 else
-    echo -e "Uh Oh!! We couldn't figure out what computer you're running..."
-    echo -e "You can probably still run the container manually though, check"
-    echo -e "out the GitHub page for help!"
-    echo -e "\n\thttps://github.com/derickson2402/Dockerized-CAEN"
-    exit
+    echo -e "$MESSAGE_OS_ERROR" && exit 1
 fi
 
-# Process the CLI args, set default vars, and get the specified program
-if [ $# -eq 0 ]; then
-    echo -e "$HELP_MESSAGE" && exit
+# Check for updates if we have an internet connection
+if ( wget -q --spider ${CAEN_URL} ); then
+    CAEN_LATEST_VERSION=$(wget -qO- \
+        "https://api.github.com/repos/derickson2402/dockerized-caen/releases/latest" \
+        | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
+    if [[ -z ${CAEN_LATEST_VERSION} ]]; then
+        echo -e "Hold up! Could not find latest version of script from GitHub" \
+            && exit 1
+    elif [[ ${CAEN_SCRIPT_VER} != ${CAEN_LATEST_VERSION} ]]; then
+        echo -e "Heads up! There is an update available from ${CAEN_SCRIPT_VER} to ${CAEN_LATEST_VERSION}."
+        echo -e "To update, run the following:"
+        echo -e "\n    sudo $0 update\n"
+    fi
 fi
-if ( wget -q --spider http://github.com ); then
-    CAEN_DEFAULT_ARGS="$CAEN_DEFAULT_ARGS --pull always"
-fi
-PROGRAM=$1
-shift
-case $PROGRAM in
-    help)
-        echo -e "$HELP_MESSAGE" && exit
-        ;;
-    perf)
-        echo -e "Heads up! Perf requires SYS_ADMIN Docker capabilities to run."
-        echo -e "You should only do this with code that you trust!"
-        read -p "Hit [Ctrl+c] to cancel, or enter to continue" </dev/tty
-        CAEN_DEFAULT_ARGS="$CAEN_DEFAULT_ARGS --privileged --cap-add SYS_ADMIN"
-        ;;
-esac
 
 # Make sure that Docker Engine is installed and running
 if ( ! command -v docker &> /dev/null ); then
-    echo -e "Heads up! Docker is not installed on your computer!"
+    echo -e "Hold up! Docker is not installed on your computer!"
     echo -e "You can download and install it here:"
     if [[ "$HOST_OS" == "windows" ]]; then
-        echo -e "\n\thttps://docs.docker.com/desktop/#download-and-install"
+        echo -e "\n    https://docs.docker.com/desktop/#download-and-install\n"
     elif [[ "$HOST_OS" == "mac" ]]; then
-        echo -e "\n\thttps://docs.docker.com/desktop/mac/install/"
+        echo -e "\n    https://docs.docker.com/desktop/mac/install/\n"
     else
-        echo -e "\n\thttps://docs.docker.com/engine/install/"
+        echo -e "\n    https://docs.docker.com/engine/install/\n"
     fi
     exit
 elif ( ! docker stats --no-stream &> /dev/null ); then
@@ -93,21 +97,62 @@ elif ( ! docker stats --no-stream &> /dev/null ); then
     while ( ! docker stats --no-stream &> /dev/null ); do
         (( counter += 1 ))
         echo -e "Waiting for Moby the Whale to wake up..."
-        sleep 10
+        sleep 15
         if [[ counter -gt 2 ]]; then
             echo -e "Couldn't wake up Moby :("
             echo -e "Maybe try restarting Docker?"
             exit
         fi
     done
+    echo "Hi Moby!"
 fi
+
+# Process the CLI args, set default vars, and get the specified program
+if [ $# -eq 0 ]; then
+    echo -e "$MESSAGE_HELP" && exit
+fi
+PROGRAM=$1
+shift
+case $PROGRAM in
+    help)
+        echo -e "$MESSAGE_HELP" && exit
+        ;;
+    version)
+        CONT_SHA=$(docker image ls -q ${CAEN_REPO_NAME}:${CAEN_VERSION})
+        CONT_VER=$(docker image inspect --format '{{json .}}' "$CONT_SHA" |
+            perl -nle 'print $& while m{"org.opencontainers.image.version":"\K[^"]+}g')
+        echo -e "Dockerized-CAEN"
+        echo -e "Script version:    ${CAEN_SCRIPT_VER}"
+        echo -e "Container version: ${CONT_VER:=unknown}"
+        exit
+        ;;
+    update)
+        if [[ $(whoami) != "root" ]]; then
+            echo "Hold up! You can only run an update as root!"
+            echo "Try running with 'sudo'"
+            exit 1
+        fi
+        echo "Updating container environment..."
+        docker pull ${CAEN_REPO_NAME}:${CAEN_VERSION} > /dev/null
+        echo "Updating wrapper script..."
+        echo '#!/bin/bash' > /tmp/caen-update.sh
+        chmod +x /tmp/caen-update.sh
+        echo "/bin/bash -c 'wget -q https://raw.githubusercontent.com/derickson2402/Dockerized-CAEN/main/caen -O /usr/local/bin/caen && chmod +x /usr/local/bin/caen'" >> /tmp/caen-update.sh
+        /tmp/caen-update.sh && rm -f /tmp/caen-update.sh && echo "Done!" && exit
+        ;;
+    perf)
+        echo -e "Heads up! Perf requires SYS_ADMIN Docker capabilities to run."
+        echo -e "You should only do this with code that you trust!"
+        read -p "Hit [Ctrl+c] to cancel, or enter to continue" </dev/tty
+        CAEN_DEFAULT_ARGS="$CAEN_DEFAULT_ARGS --privileged --cap-add SYS_ADMIN"
+        ;;
+esac
 
 # Execute the given program and its args using the CAEN container
 # Also check for stdin, allowing for file redirection
 if [ ! -t 0 ]; then
-    eval -- docker run "$CAEN_DEFAULT_ARGS" "$CAEN_ARGS" "$CAEN_WORKING_DIR" "${CAEN_REPO_NAME:=ghcr.io/derickson2402/dockerized-caen}":"${CAEN_VERSION:=latest}" "$PROGRAM" "$@" < /dev/stdin
+    eval -- docker run "${CAEN_DEFAULT_ARGS}" "${CAEN_ARGS}" "${CAEN_WORKING_DIR}" "${CAEN_REPO_NAME}":"${CAEN_VERSION}" "${PROGRAM}" "$@" < /dev/stdin
 else
-    CAEN_DEFAULT_ARGS="$CAEN_DEFAULT_ARGS -t"
-    eval -- docker run "$CAEN_DEFAULT_ARGS" "$CAEN_ARGS" "$CAEN_WORKING_DIR" "${CAEN_REPO_NAME:=ghcr.io/derickson2402/dockerized-caen}":"${CAEN_VERSION:=latest}" "$PROGRAM" "$@"
+    CAEN_DEFAULT_ARGS="${CAEN_DEFAULT_ARGS} -t"
+    eval -- docker run "$CAEN_DEFAULT_ARGS" "${CAEN_ARGS}" "${CAEN_WORKING_DIR}" "${CAEN_REPO_NAME}":"${CAEN_VERSION}" "${PROGRAM}" "$@"
 fi
-
