Refactor script to track docker daemon state
The script used to check to make sure the docker daemon was running before doing anything else, and would exit 1 if it wasn't ready. This worked nicely but I want users to be able to update the script and hopefully get updates in the event that docker or the script has a bug.

Changed the startDocker script to just verify it is running and set an env variable. Then other scripts can selectively verify whether Docker is running. This takes more writing, but is a lot more flexible.

diff --git a/caen b/caen
--- a/caen
+++ b/caen
@@ -23,6 +23,7 @@ CAEN_USER=${CAEN_USER:="$(id -u):$(id -g)"}
 CAEN_DEFAULT_ARGS="--rm -i --name caen-${RANDOM:=1} -e TERM=${TERM:=linux} --user ${CAEN_USER}"
 CAEN_WORKING_DIR="-v '$(pwd):/code'"
 HOST_OS=unknown
+HOST_DOCKER_READY=false
 CAEN_LATEST_VERSION=${CAEN_SCRIPT_VER}
 # NOTE: there is a space at the end to force newline printing
 MESSAGE_HELP=$(cat << EOF
@@ -113,7 +114,7 @@ function checkForUpdates() {
 
 # Make sure that Docker Engine is installed and running. Provide installation
 # URL if not installed, or call host machine to launch daemon if not on
-function startDocker() {
+function checkDocker() {
     if ( ! command -v docker &> /dev/null ); then
         echo -e "Hold up! Docker is not installed on your computer!"
         echo -e "You can download and install it here:"
@@ -124,8 +125,9 @@ function startDocker() {
         else
             echo -e "\n    https://docs.docker.com/engine/install/\n"
         fi
-        exit
-    elif ( ! docker ps &> /dev/null ); then
+        return
+    fi
+    if ( ! docker ps &> /dev/null ); then
         echo -e "Waking up Moby the Whale..."
         if [[ "$HOST_OS" == "mac" ]]; then
             open /Applications/Docker.app
@@ -143,11 +145,14 @@ function startDocker() {
             if [[ counter -gt 2 ]]; then
                 echo -e "Couldn't wake up Moby :("
                 echo -e "Maybe try restarting Docker?"
-                exit
             fi
+            return
         done
         echo "Hi Moby!"
     fi
+
+    # All checks have passed, Docker is ready to go
+    HOST_DOCKER_READY=true
 }
 
 # Update the docker container environment and then update the wrapper script.
@@ -162,8 +167,12 @@ function updateCAEN() {
 
     # Check for internet connection
     if ( wget -q --spider ${CAEN_URL} ); then
-        echo "Updating container environment..."
-        docker pull ${CAEN_REPO_NAME}:${CAEN_VERSION}
+        if [[ ${HOST_DOCKER_READY} == "true" ]]; then
+            echo "Updating container environment..."
+            docker pull ${CAEN_REPO_NAME}:${CAEN_VERSION}
+        else
+            echo "Cannot update container environment, Docker not responding."
+        fi
         echo "Updating wrapper script..."
         echo '#!/bin/bash' > /tmp/caen-update.sh
         chmod +x /tmp/caen-update.sh
@@ -175,27 +184,39 @@ function updateCAEN() {
     fi
 }
 
+# Poll the Docker daemon for the current container version, and print it along
+# with the script version
+function getVersion() {
+    if [[ ${HOST_DOCKER_READY} == "true" ]]; then
+        CONT_SHA=$(docker image ls -q ${CAEN_REPO_NAME}:${CAEN_VERSION})
+        CONT_VER=$(docker image inspect --format '{{json .}}' "$CONT_SHA" |
+            perl -nle 'print $& while m{"org.opencontainers.image.version":"\K[^"]+}g')
+    fi
+    echo -e "Dockerized-CAEN"
+    echo -e "Script version:    ${CAEN_SCRIPT_VER}"
+    echo -e "Container version: ${CONT_VER:=unknown}"
+    exit
+}
+
 # Process the CLI args, set default vars, and check what program should be run.
 # This lets us give help/version info, and prompt the user for commands that
 # require elevated permissions
 function checkArgs() {
     case $1 in
         help)
-            echo -e "$MESSAGE_HELP" && exit
+            echo -e "$MESSAGE_HELP"
+            exit
             ;;
         version)
-            CONT_SHA=$(docker image ls -q ${CAEN_REPO_NAME}:${CAEN_VERSION})
-            CONT_VER=$(docker image inspect --format '{{json .}}' "$CONT_SHA" |
-                perl -nle 'print $& while m{"org.opencontainers.image.version":"\K[^"]+}g')
-            echo -e "Dockerized-CAEN"
-            echo -e "Script version:    ${CAEN_SCRIPT_VER}"
-            echo -e "Container version: ${CONT_VER:=unknown}"
-            exit
+            getVersion
             ;;
         update)
             updateCAEN
             ;;
         perf)
+            if [[ ${HOST_DOCKER_READY} != "true" ]]; then
+                exit 1
+            fi
             echo -e "Heads up! Perf requires elevated Docker privileges to run. This is"
             echo -e "dangerous, so you should only do this with code that you trust!\n"
             echo -e "Hit [Ctrl+c] to cancel, or enter to continue"
@@ -214,10 +235,13 @@ function main() {
     if [ $# -eq 0 ]; then
         echo -e "$MESSAGE_HELP" && exit
     fi
-    startDocker
+    checkDocker
     checkArgs $1
 
     # Check for stdin, allowing for file redirection to the container
+    if [ ${HOST_DOCKER_READY} != "true" ]; then
+        exit 1
+    fi
     if [ ! -t 0 ]; then
         eval -- docker run "${CAEN_DEFAULT_ARGS}" "${CAEN_ARGS}" "${CAEN_WORKING_DIR}" "${CAEN_REPO_NAME}":"${CAEN_VERSION}" "$@" < /dev/stdin
     else
